services:
  telegrambot:
    image: telegrambot
    build:
      context: .
      dockerfile: TelegramBot/Dockerfile

  database:
    image: database
    build:
      context: .
      dockerfile: Database/Dockerfile

