services:
  telegrambot:
    image: telegrambot
    build:
      context: .
      dockerfile: TelegramBot/Dockerfile

  database:
    image: database
    build:
      context: .
      dockerfile: Database/Dockerfile

  transcription:
    image: transcription
    build:
      context: .
      dockerfile: Transcription/Dockerfile

  auth:
    image: auth
    build:
      context: .
      dockerfile: Auth/Dockerfile

